#!/bin/sh

# 创建日志文件并开放写入权限
touch /tmp/pppoe_ip_history.log
chmod 666 /tmp/pppoe_ip_history.log

# 如果 UCI 配置不存在，则初始化默认值
if [ -z "$(uci get pppoe_reconn.main 2>/dev/null)" ]; then
    uci set pppoe_reconn.main=config
    uci set pppoe_reconn.main.interface='wan'
    uci set pppoe_reconn.main.delay='10'
    uci commit pppoe_reconn
fi

# 清除 LuCI 缓存以显示新菜单
rm -f /tmp/luci-indexcache

# 重启相关服务以应用更改
#/etc/init.d/rpcd restart
#/etc/init.d/uhttpd restart

exit 0